# Generates machine-local Compose build settings using trusted Windows root CAs.
# Only public certificates are exported. TLS verification remains enabled.
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
$overridePath = Join-Path $projectRoot 'docker-compose.override.yml'
$marker = '# Generated by scripts/Enable-DockerBuildTrust.ps1'
if ((Test-Path -LiteralPath $overridePath) -and
    (Get-Content -LiteralPath $overridePath -TotalCount 1) -ne $marker) {
    throw 'An existing docker-compose.override.yml is not managed by this script. Preserve and merge its settings before continuing.'
}

$trustPath = [IO.Path]::GetFullPath((Join-Path $projectRoot '.docker-local/trust'))
if (!$trustPath.StartsWith($projectRoot + [IO.Path]::DirectorySeparatorChar, [StringComparison]::OrdinalIgnoreCase)) {
    throw 'Certificate directory is outside the project.'
}
New-Item -ItemType Directory -Force -Path $trustPath | Out-Null
Get-ChildItem -LiteralPath $trustPath -Filter '*.crt' -File | ForEach-Object {
    Remove-Item -LiteralPath $_.FullName
}
$certificates = @(Get-ChildItem Cert:/LocalMachine/Root; Get-ChildItem Cert:/CurrentUser/Root) |
    Where-Object { $_.NotAfter -gt (Get-Date) -and $_.NotBefore -lt (Get-Date) } |
    Sort-Object Thumbprint -Unique
if (!$certificates) { throw 'No trusted Windows root certificates were found.' }
$bundle = [Text.StringBuilder]::new()
foreach ($cert in $certificates) {
    $pem = "-----BEGIN CERTIFICATE-----`n" +
        [Convert]::ToBase64String($cert.RawData, [Base64FormattingOptions]::InsertLineBreaks) +
        "`n-----END CERTIFICATE-----`n"
    [IO.File]::WriteAllText((Join-Path $trustPath ($cert.Thumbprint + '.crt')), $pem)
    [void]$bundle.Append($pem)
}
[IO.File]::WriteAllText((Join-Path $trustPath 'bundle.pem'), $bundle.ToString())

$yaml = [Text.StringBuilder]::new()
[void]$yaml.AppendLine($marker)
[void]$yaml.AppendLine('# Local certificates and build overrides must not be committed.')
[void]$yaml.AppendLine('services:')
foreach ($service in @('backend', 'catalog-service', 'frontend', 'cart-service')) {
    $dockerfile = [IO.File]::ReadAllText((Join-Path $projectRoot "$service/Dockerfile"))
    $firstStage = [regex]::Match($dockerfile, '(?m)^FROM[^\r\n]+\r?\n')
    if (!$firstStage.Success) { throw "No FROM instruction found for $service." }
    $injection = switch ($service) {
        'catalog-service' {
            @'
COPY --from=local_trust . /tmp/windows-ca/
RUN for cert in /tmp/windows-ca/*.crt; do keytool -importcert -noprompt -trustcacerts -cacerts -storepass changeit -alias "$(basename "$cert")" -file "$cert"; done
'@
        }
        'backend' {
            "COPY --from=local_trust . /usr/local/share/ca-certificates/`nRUN update-ca-certificates"
        }
        default {
            "COPY --from=local_trust bundle.pem /tmp/windows-ca.pem`nENV NODE_EXTRA_CA_CERTS=/tmp/windows-ca.pem"
        }
    }
    $index = $firstStage.Index + $firstStage.Length
    $inline = $dockerfile.Substring(0, $index) + $injection + "`n" + $dockerfile.Substring($index)
    [void]$yaml.AppendLine("  ${service}:")
    [void]$yaml.AppendLine('    build: !override')
    [void]$yaml.AppendLine("      context: ./$service")
    [void]$yaml.AppendLine('      additional_contexts:')
    [void]$yaml.AppendLine('        local_trust: ./.docker-local/trust')
    [void]$yaml.AppendLine('      dockerfile_inline: |')
    foreach ($line in ($inline -split '\r?\n')) {
        [void]$yaml.AppendLine('        ' + $line.Replace('$', '$$'))
    }
}
[IO.File]::WriteAllText($overridePath, $yaml.ToString())
Write-Output "Configured local build trust using $($certificates.Count) public root certificates."
Write-Output 'Now run: docker compose up -d --build'
Write-Output 'Run this script again after changing a Dockerfile or Windows root certificates.'
