server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://backend:80/api/;
    proxy_set_header Authorization $http_authorization;
  }

  location /catalog-api/ {
    proxy_pass http://catalog-service:8080/api/;
  }

  location /order-api/ {
    proxy_pass http://order-service:3000/api/;
    proxy_set_header Authorization $http_authorization;
    proxy_read_timeout 60s;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
