server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: catalog-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/catalog_db}
      auto-index-creation: true

app:
  cors:
    allowed-origins: ${FRONTEND_ORIGIN:http://localhost:4200}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never