CREATE TABLE IF NOT EXISTS Categoria (
    IdCategoria INT NOT NULL AUTO_INCREMENT,
    Descripcion VARCHAR(255) NOT NULL,
    PRIMARY KEY (IdCategoria)
);

CREATE TABLE IF NOT EXISTS Producto (
    IdProducto INT NOT NULL AUTO_INCREMENT,
    Nombre VARCHAR(150) NOT NULL,
    Descripcion VARCHAR(500) NOT NULL,
    Precio DECIMAL(10, 2) NOT NULL,
    Stock INT NOT NULL DEFAULT 0,
    ImagenUrl VARCHAR(500) NULL,
    Estado BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (IdProducto)
);

INSERT INTO Producto (Nombre, Descripcion, Precio, Stock, ImagenUrl, Estado) VALUES
('Laptop Gamer X1', 'Laptop con procesador Intel i7, 16GB RAM y tarjeta gráfica dedicada.', 2599.99, 12, 'https://example.com/images/laptop-gamer-x1.jpg', TRUE),
('Mouse Inalámbrico Pro', 'Mouse ergonómico para trabajo y gaming con sensor de alta precisión.', 49.99, 30, 'https://example.com/images/mouse-inalambrico-pro.jpg', TRUE),
('Teclado Mecánico RGB', 'Teclado mecánico con switches azules y retroiluminación RGB.', 89.99, 22, 'https://example.com/images/teclado-mecanico-rgb.jpg', TRUE),
('Monitor 27 4K', 'Monitor Ultra HD de 27 pulgadas ideal para diseño y multimedia.', 399.99, 8, 'https://example.com/images/monitor-27-4k.jpg', TRUE),
('Auriculares Bluetooth', 'Auriculares inalámbricos con cancelación de ruido y 20h de batería.', 129.99, 25, 'https://example.com/images/auriculares-bluetooth.jpg', TRUE),
('Impresora Multifunción', 'Impresora láser con escáner y copiado para oficina.', 249.99, 10, 'https://example.com/images/impresora-multifuncion.jpg', TRUE),
('Cámara Web HD', 'Cámara web Full HD para videollamadas y streaming.', 79.99, 18, 'https://example.com/images/camara-web-hd.jpg', TRUE),
('Disco SSD 1TB', 'Disco sólido de 1TB para mejor rendimiento y velocidad.', 109.99, 35, 'https://example.com/images/ssd-1tb.jpg', TRUE),
('Router WiFi 6', 'Router dual-band con tecnología WiFi 6 para alta velocidad.', 149.99, 16, 'https://example.com/images/router-wifi-6.jpg', TRUE),
('Webcam 4K', 'Webcam profesional con resolución 4K y enfoque automático.', 179.99, 14, 'https://example.com/images/webcam-4k.jpg', TRUE),
('Smart TV 50', 'Televisión inteligente de 50 pulgadas con Android TV.', 529.99, 7, 'https://example.com/images/smart-tv-50.jpg', TRUE),
('Altavoz Bluetooth Mini', 'Altavoz portátil con sonido claro y resistencia al agua.', 59.99, 28, 'https://example.com/images/altavoz-mini.jpg', TRUE),
('Tablet 10 pulgadas', 'Tablet Android con pantalla IPS y gran capacidad de almacenamiento.', 289.99, 13, 'https://example.com/images/tablet-10.jpg', TRUE),
('Smartwatch Deportivo', 'Reloj inteligente con monitor de frecuencia cardiaca y GPS.', 199.99, 19, 'https://example.com/images/smartwatch-deportivo.jpg', TRUE),
('Consola Portátil', 'Consola portátil de 8 pulgadas con juegos preinstalados.', 349.99, 9, 'https://example.com/images/consola-portatil.jpg', TRUE),
('Cargador USB-C 65W', 'Cargador rápido para laptops y dispositivos móviles.', 39.99, 40, 'https://example.com/images/cargador-usb-c.jpg', TRUE),
('Silla Gamer', 'Silla ergonómica con soporte lumbar y reposabrazos.', 239.99, 6, 'https://example.com/images/silla-gamer.jpg', TRUE),
('Escritorio Ajustable', 'Escritorio eléctrico con altura ajustable para oficina.', 459.99, 5, 'https://example.com/images/escritorio-ajustable.jpg', TRUE),
('Batería Externa 20000mAh', 'Batería de alta capacidad para cargar varios dispositivos.', 79.99, 21, 'https://example.com/images/bateria-externa.jpg', TRUE),
('Micrófono USB', 'Micrófono condensador USB para streaming y grabación.', 99.99, 17, 'https://example.com/images/microfono-usb.jpg', TRUE),
('Mochila para Laptop', 'Mochila resistente con compartimento para portátil de 15.6.', 69.99, 26, 'https://example.com/images/mochila-laptop.jpg', TRUE),
('Pendrive 128GB', 'Unidad flash USB de alta velocidad con 128GB.', 24.99, 50, 'https://example.com/images/pendrive-128gb.jpg', TRUE),
('Proyector Portátil', 'Proyector compacto con resolución HD para cine en casa.', 599.99, 4, 'https://example.com/images/proyector-portatil.jpg', TRUE),
('Placa de Video RTX', 'Tarjeta gráfica para gaming y edición profesional.', 899.99, 3, 'https://example.com/images/placa-video-rtx.jpg', TRUE),
('Memoria RAM 32GB', 'Módulo DDR4 de 32GB para rendimiento intensivo.', 139.99, 20, 'https://example.com/images/ram-32gb.jpg', TRUE),
('Base de Refrigeración', 'Base para laptop con ventiladores y soporte ergonómico.', 69.99, 15, 'https://example.com/images/base-refrigeracion.jpg', TRUE),
('Disco Duro 2TB', 'Disco duro externo de 2TB para almacenamiento masivo.', 89.99, 12, 'https://example.com/images/disco-duro-2tb.jpg', TRUE),
('Lámpara de Escritorio', 'Lámpara LED con ajuste de brillo y temperatura.', 54.99, 27, 'https://example.com/images/lampara-escritorio.jpg', TRUE),
('Extensión Eléctrica', 'Extensión de 5 tomas con protección para oficina.', 29.99, 32, 'https://example.com/images/extensiones-electricas.jpg', TRUE),
('Cámara de Acción', 'Cámara resistente para deportes y grabación en 4K.', 219.99, 11, 'https://example.com/images/camara-accion.jpg', TRUE),
('Kit de Auriculares Gamer', 'Auriculares con micrófono y sonido envolvente 7.1.', 119.99, 18, 'https://example.com/images/kit-auriculares-gamer.jpg', TRUE),
('Monitor Curvo 34', 'Monitor ultrawide curvo para multitarea y gaming.', 649.99, 5, 'https://example.com/images/monitor-curvo-34.jpg', TRUE),
('Estación de Trabajo', 'Estación de docking para conectar múltiples dispositivos.', 169.99, 14, 'https://example.com/images/estacion-trabajo.jpg', TRUE),
('Adaptador HDMI a VGA', 'Adaptador para conectar laptop o PC a proyector.', 19.99, 44, 'https://example.com/images/adaptador-hdmi-vga.jpg', TRUE),
('Mousepad XXL', 'Alfombrilla grande para gaming y precisión.', 29.99, 36, 'https://example.com/images/mousepad-xxl.jpg', TRUE),
('Soporte para Monitor', 'Soporte ajustable para montar monitor en escritorio.', 79.99, 20, 'https://example.com/images/soporte-monitor.jpg', TRUE),
('Hub USB 7 en 1', 'Hub con varios puertos USB y HDMI para laptop.', 49.99, 24, 'https://example.com/images/hub-usb-7.jpg', TRUE),
('Scanner Portátil', 'Escáner portátil compacto para documentos y facturas.', 129.99, 10, 'https://example.com/images/scanner-portatil.jpg', TRUE),
('Cámara Digital Compacta', 'Cámara digital con lente 48MP para fotos de calidad.', 259.99, 9, 'https://example.com/images/camara-digital-compacta.jpg', TRUE),
('Ventilador de Escritorio', 'Ventilador silencioso y ajustable para oficina.', 34.99, 30, 'https://example.com/images/ventilador-escritorio.jpg', TRUE),
('UPS para PC', 'Fuente de energía de respaldo para proteger equipos.', 189.99, 7, 'https://example.com/images/ups-pc.jpg', TRUE),
('Procesador Intel i9', 'Procesador de alto rendimiento para equipos gamer y de edición.', 499.99, 6, 'https://example.com/images/procesador-i9.jpg', TRUE),
('Tarjeta Madre Z590', 'Placa base compatible con Intel para PCs de alto rendimiento.', 319.99, 8, 'https://example.com/images/tarjeta-madre-z590.jpg', TRUE),
('Fuente de Poder 750W', 'Fuente modular de 750W para equipos de gaming.', 119.99, 15, 'https://example.com/images/fuente-750w.jpg', TRUE),
('Caja de PC RGB', 'Gabinete con iluminación RGB y excelente flujo de aire.', 149.99, 12, 'https://example.com/images/caja-pc-rgb.jpg', TRUE),
('Cable HDMI 2.1', 'Cable de alta velocidad para 4K y 120Hz.', 17.99, 45, 'https://example.com/images/cable-hdmi-21.jpg', TRUE),
('HDD Externo 4TB', 'Disco duro externo para backup y almacenamiento masivo.', 139.99, 11, 'https://example.com/images/hdd-externo-4tb.jpg', TRUE),
('Radio Bluetooth', 'Radio con conexión Bluetooth y batería recargable.', 64.99, 22, 'https://example.com/images/radio-bluetooth.jpg', TRUE),
('Reloj de Mesa Digital', 'Reloj digital con alarma y temperatura.', 24.99, 48, 'https://example.com/images/reloj-mesa-digital.jpg', TRUE);